name: Deploy Database Migrations

# Trigger: Run when migration files change on main branch
on:
  push:
    branches: [main]
    paths: ['supabase/migrations/**']

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the code from repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Install Supabase CLI
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      # Step 3: Link to your Supabase project
      - name: Link Supabase project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      # Step 4: Apply pending migrations to production database
      - name: Deploy migrations
        run: |
          supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}